#!/usr/bin/env python3
"""Merge the ai-roots rules into the Codex global AGENTS.md as a marker block.

Codex reads one file, not a rules directory, so the rules are concatenated rather
than symlinked. Anything the user wrote outside the markers is preserved.

usage: sync-agents-md.py <rules-dir> <agents-md-path>
"""

import sys
from pathlib import Path

BEGIN = "<!-- >>> ai-roots rules >>> -->"
END = "<!-- <<< ai-roots rules <<< -->"

HEADER = """These rules come from the ai-roots repository and are regenerated by its `install.sh`.
Edit them there, not here — anything written between the markers is overwritten on the next install.
"""


def build_block(rules_dir: Path) -> str:
    parts = [BEGIN, "", HEADER]
    for rule in sorted(rules_dir.glob("*.md")):
        parts.append(f"\n---\n\n<!-- rules/{rule.name} -->\n")
        parts.append(rule.read_text().strip())
        parts.append("")
    parts.append(END)
    return "\n".join(parts) + "\n"


def splice(existing: str, block: str) -> str:
    start = existing.find(BEGIN)
    end = existing.find(END)
    if start == -1 or end == -1 or end < start:
        prefix = existing.rstrip()
        return f"{prefix}\n\n{block}" if prefix else block
    return existing[:start] + block + existing[end + len(END) :].lstrip("\n")


def main() -> int:
    if len(sys.argv) != 3:
        print(__doc__.strip(), file=sys.stderr)
        return 2
    rules_dir, target = Path(sys.argv[1]), Path(sys.argv[2])
    if not rules_dir.is_dir():
        print(f"error: rules source not found: {rules_dir}", file=sys.stderr)
        return 1
    existing = target.read_text() if target.exists() else ""
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(splice(existing, build_block(rules_dir)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
